# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[build]
  publish = "_site"
  command = "jekyll build"

[[plugins]]
  package = "netlify-plugin-jekyll-cache"

	[plugins.inputs]

    # This is only required if you have defined a source directory in Jekyll
    # At some point this will become automated, but for now it must be specified 
	jekyllSource = "/jekyll"
